### ISSUE TITLE
Spring graal native

### ISSUE THREAD

**Issue by ebaptistella** [LeonardoWiest/spring-boot-graalvm#3]
Já testou essa dependência @LeonardoWiest
```
<groupId>org.springframework.experimental</groupId>
<artifactId>spring-graal-native</artifactId>
```

Experimental ainda, mas parece que vai facilitar um pouco.
[https://spring.io/blog/2020/04/16/spring-tips-the-graalvm-native-image-builder-feature ](url)

**Comment by LeonardoWiest** [comment]
@ebaptistella ... sim, vamos verificar essa dependência. Obrigado.

**Comment by LeonardoWiest** [comment]
Passamos a utilizar essa dependência @ebaptistella.
